# =============================================================================
# Streamlit App
# =============================================================================
# Script Purpose:
#     This script is responsible for creating a live Streamlit dashboard that
#     displays real-time pos event data from Kafka. 
# =============================================================================

import os
import time
import sys
import requests
import streamlit as st
import pandas as pd
from supabase import create_client

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from utils.utils import get_current_profile

query_dict = {
    "Total Orders": "v_total_orders",
    "Total Revenue": "v_total_revenue",
    "Average Order Duration": "v_avg_order_duration",
    "Average Spend Per Head": "v_avg_spend_per_head",
    "Alert Count": "v_alert_count",
    "Rev Over Time": "v_revenue_over_time",
    "Top Items": "v_top_items",
    "Server Metrics": "v_server_metrics",
    "Recent Alerts": "v_recent_alerts"
}

def run_query(view_name):
    """
    Queries a Supabase view via the REST API and returns the result as a pandas DataFrame.
    """
    url = f"{st.secrets['SUPABASE_URL']}/rest/v1/{view_name}"
    headers = {
        "apikey": st.secrets["SUPABASE_KEY"],
        "Authorization": f"Bearer {st.secrets['SUPABASE_KEY']}"
    }
    response = requests.get(url, headers=headers)
    return pd.DataFrame(response.json())

st.markdown("""<style>
            [data-testid="stMetric"] {
                border-radius: 8px;
                padding: 12px;
            }

            [data-testid="stMetricValue"] {
                color: #7DBBF3;
            }
            </style>""", unsafe_allow_html=True)

st.set_page_config(layout="wide", page_icon="🍽️", page_title="Restaurant POS Event Simulator")
st.title("Restaurant POS Event Simulator")
st.caption("Real-time restaurant POS event stream built with Kafka, Avro, Schema Registry, and PostgreSQL. Events are generated by a simulator, processed by two independent consumer groups, and visualized here as they arrive.")

if get_current_profile() is None:
    st.warning("The restaurant is currently closed. Historical data is shown.")
else:
    st.success("The restaurant is currently open. Dashboard will update in real-time.")

st.markdown("---")

# KPIs
col1, col2, col3, col4, col5 = st.columns(5)

with col1:
    df = run_query(query_dict["Total Orders"])
    value = int(df.iloc[0, 0]) if not df.empty else 0
    st.metric("Total Tables", value=value, border=True)

with col2:
    df = run_query(query_dict["Total Revenue"])
    value = df.iloc[0, 0] if not df.empty else 0
    st.metric("Total Revenue", value=value, format="dollar", border=True)

with col3:
    df = run_query(query_dict["Average Order Duration"])
    value = round(float(df.iloc[0, 0]), 2) if not df.empty else 0
    st.metric("Average Table Duration", f"{value} min", border=True)

with col4:
    df = run_query(query_dict["Average Spend Per Head"])
    value = round(float(df.iloc[0, 0]), 2) if not df.empty else 0
    st.metric("Average Spend Per Head", value=value, format="dollar", border=True)

with col5:
    df = run_query(query_dict["Alert Count"])
    value = int(df.iloc[0, 0]) if not df.empty else 0
    st.metric("Alert Count", value=value, border=True)


# Charts
col1, col2 = st.columns([5, 6])
with col1:
    st.write("## Revenue Over Time")
    df = run_query(query_dict["Rev Over Time"])
    if df.empty or "running_total" not in df.columns or df["running_total"].sum() == 0:
        st.info("Waiting for payment data...")
    else:
        df["running_total"] = df["running_total"].astype(float)
        df["minute_timestamp"] = pd.to_datetime(df["minute_timestamp"])
        if df["minute_timestamp"].dt.date.nunique() > 1:
            df["minute_timestamp"] = df["minute_timestamp"].dt.strftime("%b %-d %I:%M %p")
        else:
            df["minute_timestamp"] = df["minute_timestamp"].dt.strftime("%I:%M %p")
        st.line_chart(data=df,
                    x="minute_timestamp",
                    y="running_total",
                    x_label="Time",
                    y_label="Revenue",
        )
with col2:
    st.write("## Best Selling Items")
    df = run_query(query_dict["Top Items"])
    if df.empty:
        st.info("Waiting for item data...")
    else:
        st.bar_chart(data=df, 
                    x="item_name", 
                    y="count", 
                    x_label="Item",
                    y_label="Quantity Sold",
                    horizontal=True,
                    sort='-count',
                    height='stretch')
        
# Tables
col1, col2 = st.columns([6, 5])
with col1:
    st.write("## Server Metrics")
    df = run_query(query_dict["Server Metrics"])
    if df.empty:
        st.info("Waiting for metrics...")
    else:
        df["Average Revenue per Table"] = df["total_revenue"] / df["table_count"]
        df["Average Table Duration"] = df["total_duration_minutes"] / df["table_count"]
        df = df.drop(columns=['total_duration_minutes'])
        df = df.rename(columns={
            "server_name": "Server Name",
            "table_count": "Tables Served",
            "total_covers": "Total Guests",
            "total_revenue": "Total Revenue"
        })
        st.dataframe(data=df.style
                    .background_gradient(subset=["Total Revenue"], cmap="Greens")
                    .background_gradient(subset=["Average Revenue per Table"], cmap="Greens")
                    .background_gradient(subset=["Average Table Duration"], cmap="autumn_r"),
                    hide_index=True,
                    column_config={
                        "Total Revenue": st.column_config.NumberColumn(format="$%.2f"),
                        "Average Revenue per Table": st.column_config.NumberColumn(format="$%.2f"),
                        "Average Table Duration": st.column_config.NumberColumn(format="%.2f min")}
        )


with col2:
    st.write("## Recent Alerts")
    df = run_query(query_dict["Recent Alerts"])
    if df.empty:
        st.info("Waiting for alert data...")
    else:
        df = df.rename(columns={
            "message": "Message",
            "triggered_at": "Time"
        })
        st.dataframe(data=df,
                    hide_index=True,
                    column_order=["Time", "Message"],
                    column_config={
                        "Time": st.column_config.DatetimeColumn(format="D MMM YYYY, h:mm a")
                    }
        )

st.markdown("---")
st.caption(f"Last updated: {pd.Timestamp.now().strftime('%B %-d, %Y at %I:%M %p')} MT")
st.caption("Built by Angela Lekivetz | [GitHub](https://github.com/alekivetz) | [Portfolio](https://alekivetz.github.io/)")

time.sleep(60)
st.rerun()