# =============================================================================
# Streamlit App
# =============================================================================
# Script Purpose:
#     This script is responsible for creating a live Streamlit dashboard that
#     displays real-time pos event data from Kafka. 
# =============================================================================

import os
import time
import sys
import psycopg2
import streamlit as st
import pandas as pd

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from utils.utils import get_current_profile

if get_current_profile() is None:
    st.warning("The restaurant is currently closed. Showing data from the previous day.")
else:
    st.success("The restaurant is currently open. Dasbboard data is real-time.")

@st.cache_resource
def get_connection(): 
    """
    Establishes a connection to the Postgres database and returns a psycopg2 connection object.
    """  
    return psycopg2.connect(
        host=st.secrets["DB_HOST"],
        port=st.secrets["DB_PORT"],
        database=st.secrets["DB_NAME"],
        user=st.secrets["DB_USER"],
        password=st.secrets["DB_PASSWORD"]
    )

def run_query(query):
    """
    Opens a new cursor, runs the provided query, and returns the result as a pandas DataFrame.
    """
    conn = get_connection()
    try:
        cur = conn.cursor()
        cur.execute(query)
        result = cur.fetchall()
        df = pd.DataFrame(result, columns=[desc[0] for desc in cur.description])
        cur.close()
        return df
    except Exception as e:
        conn.rollback()
        st.error(f"Query failed: {e}")
        return pd.DataFrame()



st.markdown("""<style>
            [data-testid="stMetric"] {
                border-radius: 8px;
                padding: 12px;
            }

            [data-testid="stMetricValue"] {
                color: #7DBBF3;
            }
            </style>""", unsafe_allow_html=True)

st.set_page_config(layout="wide", page_icon="🍽️", page_title="Restaurant POS Event Simulator")

st.title("Restaurant POS Event Simulator")
st.caption("Real-time restaurant POS event stream built with Kafka, Avro, Schema Registry, and PostgreSQL. Events are generated by a simulator, processed by two independent consumer groups, and visualized here as they arrive.")
st.markdown("---")

query_dict = {
    "Total Orders": "SELECT COALESCE(SUM(order_count), 0) FROM minute_metrics",
    "Total Revenue": "SELECT COALESCE(SUM(total_revenue), 0) FROM minute_metrics",
    "Average Order Duration": "SELECT COALESCE(AVG(table_duration_minutes), 0) FROM recent_payments",
    "Average Spend Per Head": "SELECT COALESCE(AVG(total_amount / table_size), 0) FROM recent_payments",
    "Alert Count": "SELECT COUNT(*) FROM alerts",
    "Rev Over Time": """
        SELECT minute_timestamp, 
            total_revenue,
            SUM(total_revenue) OVER (ORDER BY minute_timestamp) as running_total
        FROM (
            SELECT 
                minute_timestamp AT TIME ZONE 'UTC' AT TIME ZONE 'America/Edmonton' as minute_timestamp,
                SUM(total_revenue) as total_revenue
            FROM minute_metrics
            GROUP BY minute_timestamp
            ) sub
        ORDER BY minute_timestamp ASC
        LIMIT 30
    """,
    "Top Items": "SELECT item_name, category, count FROM item_counts ORDER BY count DESC LIMIT 10",
    "Server Metrics": """ SELECT * FROM server_metrics ORDER BY total_revenue DESC""",
    "Recent Alerts": """ 
        SELECT
            triggered_at AT TIME ZONE 'UTC' AT TIME ZONE 'America/Edmonton' as triggered_at,
            message
        FROM alerts 
        ORDER BY triggered_at DESC LIMIT 10"""
}

# KPIs
col1, col2, col3, col4, col5 = st.columns(5)

with col1:
    df = run_query(query_dict["Total Orders"])
    value = int(df.iloc[0, 0]) if not df.empty else 0
    st.metric("Total Tables", value=value, border=True)

with col2:
    df = run_query(query_dict["Total Revenue"])
    value = df.iloc[0, 0] if not df.empty else 0
    st.metric("Total Revenue", value=value, format="dollar", border=True)

with col3:
    df = run_query(query_dict["Average Order Duration"])
    value = round(float(df.iloc[0, 0]), 2) if not df.empty else 0
    st.metric("Average Table Duration", f"{value} min", border=True)

with col4:
    df = run_query(query_dict["Average Spend Per Head"])
    value = round(float(df.iloc[0, 0]), 2) if not df.empty else 0
    st.metric("Average Spend Per Head", value=value, format="dollar", border=True)

with col5:
    df = run_query(query_dict["Alert Count"])
    value = int(df.iloc[0, 0]) if not df.empty else 0
    st.metric("Alert Count", value=value, border=True)


# Charts
col1, col2 = st.columns(2)
with col1:
    st.write("## Revenue Over Time")
    df = run_query(query_dict["Rev Over Time"])
    if df.empty:
        st.info("Waiting for revenue data...")
    else:
        df["running_total"] = df["running_total"].astype(float)
        st.line_chart(data=df,
                    x="minute_timestamp",
                    y="running_total",
                    x_label="Time",
                    y_label="Revenue",
        )
with col2:
    st.write("## Best Selling Items")
    df = run_query(query_dict["Top Items"])
    if df.empty:
        st.info("Waiting for item data...")
    else:
        st.bar_chart(data=df, 
                    x="item_name", 
                    y="count", 
                    x_label="Item",
                    y_label="Quantity Sold",
                    horizontal=True,
                    sort='-count',
                    height='stretch')
        
# Tables
col1, col2 = st.columns(2)
with col1:
    st.write("## Server Metrics")
    df = run_query(query_dict["Server Metrics"])
    if df.empty:
        st.info("Waiting for metrics...")
    else:
        df["Average Revenue per Table"] = df["total_revenue"] / df["table_count"]
        df["Average Table Duration"] = df["total_duration_minutes"] / df["table_count"]
        df = df.drop(columns=['total_duration_minutes'])
        df = df.rename(columns={
            "server_name": "Server Name",
            "table_count": "Tables Served",
            "total_covers": "Total Guests",
            "total_revenue": "Total Revenue"
        })
        st.dataframe(data=df.style
                    .background_gradient(subset=["Total Revenue"], cmap="Greens")
                    .background_gradient(subset=["Average Revenue per Table"], cmap="Greens")
                    .background_gradient(subset=["Average Table Duration"], cmap="autumn_r"),
                    hide_index=True,
                    column_config={
                        "Total Revenue": st.column_config.NumberColumn(format="$%.2f"),
                        "Average Revenue per Table": st.column_config.NumberColumn(format="$%.2f"),
                        "Average Table Duration": st.column_config.NumberColumn(format="%.2f min")}
        )


with col2:
    st.write("## Recent Alerts")
    df = run_query(query_dict["Recent Alerts"])
    if df.empty:
        st.info("Waiting for alert data...")
    else:
        df = df.rename(columns={
            "message": "Message",
            "triggered_at": "Time"
        })
        st.dataframe(data=df,
                    hide_index=True,
                    column_order=["Time", "Message"],
                    column_config={
                        "Time": st.column_config.DatetimeColumn(format="D MMM YYYY, h:mm a")
                    }
        )

st.markdown("---")
st.caption(f"Last updated: {pd.Timestamp.now().strftime('%B %-d, %Y at %I:%M %p')} MT")
st.caption("Built by Angela Lekivetz | [GitHub](https://github.com/alekivetz) | [Portfolio](https://alekivetz.github.io/)")

time.sleep(60)
st.rerun()